### ISSUE TITLE
Wishes regarding deletion of the islands

### ISSUE THREAD

**Issue by TobiasHempel** [uskyblock/uSkyBlock#17]
_Please paste the output from `/usb version` below_
 Name: uSkyBlock
 Version: 2.8.10
 Description: Ultimate SkyBlock v2.8.10-f8b9b27
 Language: de (de)
  State: d=128, r=64, i=158, p=176, n=true, awe=true
 Server: Paper git-Paper-439 (MC: 1.16.5)
 State: online=true, bungee=true
------------------------------
Vault 1.7.3-b131 (ENABLED)
WorldEdit 7.3.0-SNAPSHOT+5599-c4efc8b (ENABLED)
WorldGuard 7.0.5-SNAPSHOT+2090-cbb3212 (ENABLED)
Multiverse-Core 4.2.3-SNAPSHOT-b822 (ENABLED)
Multiverse-NetherPortals 4.2.2-SNAPSHOT-b795 (ENABLED)

_What steps will reproduce the problem?_
Good evening,
I have the following request:
Would it be possible to delete an island (Either by name or player) so that the whole island is gone and another island can be created in the same place? Also, my wish would be that this could also be triggered via API. 
If you have any questions about this, please feel free to ask. Thank you for the plugin, we use it very gladly!

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: -

(Not following the template will result in closing the issue.)

**Comment by Muspah** [comment]
See https://www.spigotmc.org/threads/uskyblock.38300/page-141#post-4113199

**Comment by minoneer** [comment]
This was resolved in the spigot forums:

> Oh sorry, noticed your issue on Github but failed to respond. It should be possible via /usb island delete. It's not in the API, but if you import the uSkyBlock-Core package from our repository, it should be possible to call the correct methods. See the AdminIslandCommand-class for our implementation.

> (IIRC you're using the latest version, this topic is linked to the old resource that's not being updated anymore. The new thread can be found [here](https://www.spigotmc.org/resources/uskyblock-revived.66795/))

closing the issue.
