### ISSUE TITLE
MultiverseHook registerNetherworld NullPointerException

### ISSUE THREAD

**Issue by BlackBeltPanda** [uskyblock/uSkyBlock#2]
_Please paste the output from `/usb version` below_
```
Version: 2.8.9
Description: Ultimate SkyBlock v2.8.9-a693011
Language: en_GB (en_GB)
  State: d=500, r=152, i=4,604, p=16,016, n=false, awe=false
Server: Paper git-Paper-133 (MC: 1.16.1)
  State: online=true, bungee=true
------------------------------
Vault 1.7.3-b${env.TRAVIS_BUILD_NUMBER} (N/A)
WorldEdit 7.2.0-beta-02+d10d7d6 (N/A)
WorldGuard 7.0.4-beta1;bc551da (N/A)
Multiverse-Core 4.1.0-b775 (N/A)
Multiverse-NetherPortals 4.1.0-b763 (N/A)
------------------------------
```

_What steps will reproduce the problem?_
1. Start the server and the error appears once 
2. Login and the error spams the console

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* Error: https://pastebin.com/raw/P801xDnC

Tested with Multiverse-Core 4.1.1 and Multiverse-NetherPortals 4.1.1, as well. Same error with those versions.

**Comment by Muspah** [comment]
Hmm, that's odd. There used to be some code that executes the mv import command if mvCore is null, but that shouldn't be the case here. Sounded like legacy code from before MV offered an API. 

The skyworld is registered before skyworld_nether using the same MV API, is the first stacktrace logged about registerNetherworld or registerOverworld?

**Comment by BlackBeltPanda** [comment]
The only one logged is the one I posted, unfortunately. I have the nether disabled in the skyblock config, as well.

**Comment by BlackBeltPanda** [comment]
I took a quick look and it looks like the multiverse hook is being called in WorldManager (getNetherWorld()) outside the Settings.nether_enabled check. Should that be the case?

**Comment by Muspah** [comment]
Hmm, that shouldn't be the case indeed.

**Comment by Muspah** [comment]
Only have my old Thinkpad with me atm, but the fix should be easy. If you prefer a Travis build: https://www.uskyblock.ovh/downloads/master/uSkyBlock/uSkyBlock-2.8.10-SNAPSHOT.jar
