### ISSUE TITLE
EssentialsChat

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [uskyblock/uSkyBlock#38]
Is there a way to add island level as prefix? I tried everything :(

**Comment by TDMidkwhatisxd** [comment]
dead plugin, i will switch it

**Comment by Muspah** [comment]
All right...

I'm not sure where EssentialsChat gets it's placeholders from. We're supporting PAPI and will add additional placeholders in the near future.

**Comment by TDMidkwhatisxd** [comment]
I use LPC and PlaceholderAPI, when i used your plugin, it gave some errors in console, like .player null, dont have the whole error, anyway the other plugin works fine.
