### ISSUE TITLE
Swampland-biome not show in GUI

### ISSUE THREAD

**Issue by M1904** [uskyblock/uSkyBlock#47]
Name: uSkyBlock
Version: 3.0.0
Description: Ultimate SkyBlock v3.0.0-6710732
Language: de (de)
State: d=128, r=64, i=95, p=99, n=true, awe=false
Server: Paper git-Paper-484 (MC: 1.19.4)
State: online=true, bungee=true
------------------------------
Vault 1.7.3-b131 (ENABLED)
FastAsyncWorldEdit 2.6.0-SNAPSHOT-394;508b94d (WRONG-VERSION)
WorldGuard 7.0.8-SNAPSHOT+2231-bddfbdd (ENABLED)
FastAsyncWorldEdit 2.6.0-SNAPSHOT-394;508b94d (ENABLED)
Multiverse-Core 4.3.2-SNAPSHOT-b870 (ENABLED)
Multiverse-NetherPortals 4.2.2-b807 (ENABLED)
------------------------------

_What steps will reproduce the problem?_
1. open the is-menu with /is
2. click the biome-slot
3. there are 8 biomes but no lily_pad for change the biome to swampland. but the permission usb.biome.swampland is given (also tried usb.biome.swamp)

**Comment by minoneer** [comment]
This issue was fixed a while ago: https://github.com/uskyblock/uSkyBlock/commit/5e68ef49c87a4935cf43dbc7910babf2ff1dd027

The correct permission is now usb.biome.swamp
