### ISSUE TITLE
Maven Repository Offline

### ISSUE THREAD

**Issue by endercrest** [uskyblock/uSkyBlock#57]
Hey! I am in the process of updating my plugin ([VoidSpawn](https://www.spigotmc.org/resources/voidspawn.19350/)) and it looks like the maven repo that has the API for uSkyBlock hosted is offline / returning 502 bad gateway errors.

https://www.uskyblock.ovh/maven/uskyblock/

As a suggestion, it may not be a bad idea to apply for having your plugin hosted on [CodeMC](https://github.com/CodeMC) for you.

**Comment by minoneer** [comment]
Thanks for the heads-up! The repository is running again.
